# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 14:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprasial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='appraisal value')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024, null=True, verbose_name='comment text')),
                ('material_path', models.CharField(max_length=40, null=True, verbose_name='material path')),
                ('count_of_childs', models.IntegerField(default=0, verbose_name='count of childs')),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='film title')),
                ('description', models.CharField(max_length=4096, null=True, verbose_name='film description')),
                ('premier', models.DateField(default=datetime.datetime.now, verbose_name='film premier date')),
                ('rating', models.FloatField(null=True, verbose_name='film rating')),
                ('count_of_appraisal', models.IntegerField(default=0, verbose_name='film count of appraisal')),
                ('date_of_addition', models.DateField(default=datetime.datetime.now, verbose_name='film date of addition')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='film is deleted')),
                ('count_of_root_comments', models.IntegerField(default=0, verbose_name='count of root comments')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='user name')),
                ('surname', models.CharField(max_length=255, verbose_name='user surname')),
                ('patronymic', models.CharField(max_length=255, verbose_name='user patronymic')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='user email')),
                ('avatar_url', models.CharField(max_length=255, null=True, verbose_name='avatar url')),
                ('avatar', models.ImageField(null=True, upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='filmApp.Profile', verbose_name='comment author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_film', to='filmApp.Film', verbose_name='comment film'),
        ),
        migrations.AddField(
            model_name='apprasial',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_author', to='filmApp.Profile', verbose_name='appraisal author'),
        ),
        migrations.AddField(
            model_name='apprasial',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_film', to='filmApp.Film', verbose_name='appraisal film'),
        ),
    ]
