# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apprasial',
            new_name='Appraisal',
        ),
    ]
