# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0004_auto_20170218_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.IntegerField(default=0, verbose_name='level of depth of comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='material_path',
            field=models.CharField(max_length=10, null=True, verbose_name='material path'),
        ),
    ]
