# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0006_auto_20170218_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='material_path',
            field=models.CharField(default='aaaaa', max_length=10, verbose_name='material path'),
        ),
    ]
