# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0007_auto_20170218_1414'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('myManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
