# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0008_auto_20170218_1415'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appraisal',
            managers=[
                ('customManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('customManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='count_of_comments',
            field=models.IntegerField(default=0, verbose_name='count of comments'),
        ),
    ]
