# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0009_auto_20170219_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='time of comment'),
        ),
    ]
