# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0010_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(default='USA', max_length=255, verbose_name='Country'),
        ),
    ]
