# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0011_film_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='premier',
            new_name='premiere',
        ),
    ]
