# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0012_auto_20170219_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='producer',
            field=models.CharField(default='N/a', max_length=255, verbose_name='Producer'),
        ),
    ]
