# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0013_film_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reverse_level',
            field=models.IntegerField(default=12, verbose_name='value contrary to the level'),
        ),
    ]
