# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0014_comment_reverse_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(default=0, verbose_name='film rating'),
        ),
    ]
