# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0016_auto_20170221_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isModerator',
            field=models.BooleanField(default=False, verbose_name='This user has moderators rights'),
        ),
    ]
